name: Scan 

on:
  push:
  workflow_dispatch:

jobs:
  scan:
    uses: melissa-commits/actions/.github/workflows/iac_scan_test.yml@main
     permissions:  # 👈 Grant the permissions the called workflow requests
      actions: read
      contents: read
      security-events: write

