name: Scan 

on:
  push:
  workflow_dispatch:

jobs:
  scan:
    uses: melissa-commits/actions/.github/workflows/iac_scan_test.yml@main
    permissions:
      contents: read
      security-events: write  
